### ISSUE TITLE
Error when trying to install libfchat

### ISSUE THREAD

**Issue by ghost** [rgooler/libfchat-ruby#6]
First of all, I have Ruby 1.9.3-p551 and DevKit-tdm-32-4.5.2-20111229-1559-sfx installed.

When I try to install your gem with
gem install libfchat
what I get is

Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing libfchat:
        ERROR: Failed to build gem native extension.

    "D:/Program Files/Ruby193/bin/ruby.exe" -r ./siteconf20150726-6720-i5h32t.rb
 extconf.rb
checking for main() in -lssl... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... yes
checking for ruby/thread.h... no
checking for inotify_init() in sys/inotify.h... no
checking for __NR_inotify_init in sys/syscall.h... no
checking for writev() in sys/uio.h... no
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... yes
checking for rb_time_new()... yes
checking for windows.h... yes
checking for winsock.h... yes
checking for main() in -lkernel32... yes
checking for main() in -lrpcrt4... yes
checking for main() in -lgdi32... yes
checking for clock_gettime()... no
checking for gethrtime()... no
creating Makefile

make  clean
Makefile:165: *** target pattern contains no `%'.  Stop.

make
Makefile:165: *** target pattern contains no `%'.  Stop.

make failed, exit code 2

Gem files will remain installed in D:/Program Files/Ruby193/lib/ruby/gems/1.9.1/
gems/eventmachine-1.0.7 for inspection.
Results logged to D:/Program Files/Ruby193/lib/ruby/gems/1.9.1/extensions/x86-mi
ngw32/1.9.1/eventmachine-1.0.7/gem_make.out

**Comment by rgooler** [comment]
Can you please attach the log file mentioned at the end of your report, as
well as the generated make file?

Also, this is doing things in program files - try again as an administrator?

**Comment by CanoasTC** [comment]
I managed to fix the eventmachine problem by installing eventmachine v 1.0.3
Now it returns a similar error, but the problem being with Faye-Websocket 0.4.7

Here's the error:
http://pastebin.com/H5UdQFpy
(the log at the end is just a copy of the error)

Here's the makefile:
https://www.dropbox.com/s/bbmrcrfnn27h749/Makefile?dl=0

I just did a clean reinstall of ruby 193 and the devkit. I tried to install libfchat, getting the same eventmachine error as before, which I once again fixed by installing eventmachine v 1.0.3. 

In case it's useful, these are the gems I have installed (gem list)
bigdecimal (1.1.0)
eventmachine (1.0.3 x86-mingw32)
io-console (0.3)
json (1.5.5)
minitest (2.5.1)
multi_json (1.3.7)
rake (0.9.2.2)
rdoc (3.9.5)
rubygems-update (2.4.8)
websocket-extensions (0.1.2)


Do you think you could check the versions of your gems? Maybe if I just install the same versions as you it'll be fine. Hopefully.
